export const CHURCH_INTELLIGENCE_AUDIT = {
  HEALTH_CALCULATED: 'CHURCH_HEALTH_CALCULATED',
  REPORT_GENERATED: 'CHURCH_INTELLIGENCE_REPORT_GENERATED',
  ALERTS_GENERATED: 'CHURCH_GOVERNANCE_ALERTS_GENERATED',
  LEADERSHIP_ANALYTICS_VIEWED: 'CHURCH_LEADERSHIP_ANALYTICS_VIEWED',
  TERM_UPSERTED: 'CHURCH_LEADERSHIP_TERM_UPSERTED',
} as const;

export const CHURCH_INTELLIGENCE_AUDIT_ENTITY = {
  CHURCH: 'CHURCH',
  MINISTRY: 'MINISTRY',
  OPERATIONAL_UNIT: 'OPERATIONAL_UNIT',
  MEMBER: 'MEMBER',
  LEADERSHIP_TERM: 'LEADERSHIP_TERM',
} as const;

export const HEALTH_STATUS_THRESHOLDS = {
  EXCELLENT: 85,
  HEALTHY: 70,
  WATCHLIST: 50,
  AT_RISK: 25,
} as const;
