export const MEMBER_PORTAL_AUDIT = {
  JOIN_REQUEST_SUBMITTED: 'CHOIR_JOIN_REQUEST_SUBMITTED',
  JOIN_REQUEST_REVIEWED: 'CHOIR_JOIN_REQUEST_REVIEWED',
  PROTOCOL_INVITATION_SENT: 'PROTOCOL_INVITATION_SENT',
  PROTOCOL_INVITATION_RESPONDED: 'PROTOCOL_INVITATION_RESPONDED',
  PROTOCOL_CLAIM_SUBMITTED: 'PROTOCOL_CLAIM_SUBMITTED',
  PROTOCOL_CLAIM_REVIEWED: 'PROTOCOL_CLAIM_REVIEWED',
  BROADCAST_CREATED: 'CHURCH_BROADCAST_CREATED',
} as const;

/** Yerusalemu morning service choir — may pair with one primary choir */
export const YERUSALEMU_CHOIR_CODE = 'YERUSALEMU';

export const PRIMARY_CHOIR_CODES = [
  'IJWI_RY_UMWAMI',
  'ELIM',
  'INTEGUZA',
  'EL_BETHEL',
  'BEULAH',
  'CHILDREN_CHOIR',
] as const;
