import { ProtocolAssignmentMode } from '@prisma/client';

export const PROTOCOL_AUDIT = {
  TEAM_GENERATED: 'PROTOCOL_TEAM_GENERATED',
  TEAM_STATUS: 'PROTOCOL_TEAM_STATUS',
  ASSIGNMENT_OVERRIDE: 'PROTOCOL_ASSIGNMENT_OVERRIDE',
  ATTENDANCE_RECORDED: 'PROTOCOL_ATTENDANCE_RECORDED',
  ATTENDANCE_MODIFIED: 'PROTOCOL_ATTENDANCE_MODIFIED',
  REPLACEMENT_REQUESTED: 'PROTOCOL_REPLACEMENT_REQUESTED',
  REPLACEMENT_REVIEWED: 'PROTOCOL_REPLACEMENT_REVIEWED',
  RANKING_GENERATED: 'PROTOCOL_RANKING_GENERATED',
  CATEGORY_RANKING_GENERATED: 'PROTOCOL_CATEGORY_RANKING_GENERATED',
  REPORT_EXPORTED: 'PROTOCOL_REPORT_EXPORTED',
  PROFILE_UPDATED: 'PROTOCOL_PROFILE_UPDATED',
  TEAM_LEADER_CREATED: 'PROTOCOL_TEAM_LEADER_CREATED',
  TEAM_LEADER_UPDATED: 'PROTOCOL_TEAM_LEADER_UPDATED',
  TEAM_LEADER_ASSIGNED: 'PROTOCOL_TEAM_LEADER_ASSIGNED',
  TEAM_REPORT_SUBMITTED: 'PROTOCOL_TEAM_REPORT_SUBMITTED',
} as const;

export const PROTOCOL_AUDIT_ENTITY = 'ProtocolOccurrenceTeam';

export const PROTOCOL_UNIT_CODE = 'PROTOCOL_TEAM';

export const TEMPLATE_ASSIGNMENT_MODES: Record<string, ProtocolAssignmentMode> = {
  SUNDAY_SERVICE_1: 'SUNDAY',
  SUNDAY_SERVICE_2: 'SUNDAY',
  TUESDAY_SERVICE: 'TUESDAY',
  IGABURO: 'IGABURO',
};

export function resolveAssignmentMode(
  templateCode: string | null | undefined,
  operationType: string,
): ProtocolAssignmentMode {
  if (templateCode && TEMPLATE_ASSIGNMENT_MODES[templateCode]) {
    return TEMPLATE_ASSIGNMENT_MODES[templateCode];
  }
  return operationType === 'SPECIAL_EVENT' ? 'SPECIAL_EVENT' : 'TUESDAY';
}
