import { ProtocolAssignmentMode } from '@prisma/client';

export const PROTOCOL_AUDIT = {
  TEAM_GENERATED: 'PROTOCOL_TEAM_GENERATED',
  TEAM_STATUS: 'PROTOCOL_TEAM_STATUS',
  ASSIGNMENT_OVERRIDE: 'PROTOCOL_ASSIGNMENT_OVERRIDE',
  ATTENDANCE_RECORDED: 'PROTOCOL_ATTENDANCE_RECORDED',
  ATTENDANCE_MODIFIED: 'PROTOCOL_ATTENDANCE_MODIFIED',
  REPLACEMENT_REQUESTED: 'PROTOCOL_REPLACEMENT_REQUESTED',
  REPLACEMENT_REVIEWED: 'PROTOCOL_REPLACEMENT_REVIEWED',
  RANKING_GENERATED: 'PROTOCOL_RANKING_GENERATED',
  CATEGORY_RANKING_GENERATED: 'PROTOCOL_CATEGORY_RANKING_GENERATED',
  REPORT_EXPORTED: 'PROTOCOL_REPORT_EXPORTED',
  PROFILE_UPDATED: 'PROTOCOL_PROFILE_UPDATED',
  TEAM_LEADER_CREATED: 'PROTOCOL_TEAM_LEADER_CREATED',
  TEAM_LEADER_UPDATED: 'PROTOCOL_TEAM_LEADER_UPDATED',
  TEAM_LEADER_ASSIGNED: 'PROTOCOL_TEAM_LEADER_ASSIGNED',
  TEAM_REPORT_SUBMITTED: 'PROTOCOL_TEAM_REPORT_SUBMITTED',
  DOCUMENT_UPLOADED: 'PROTOCOL_DOCUMENT_UPLOADED',
} as const;

export const PROTOCOL_AUDIT_ENTITY = 'ProtocolOccurrenceTeam';

export const PROTOCOL_UNIT_CODE = 'PROTOCOL_TEAM';

export const TEMPLATE_ASSIGNMENT_MODES: Record<string, ProtocolAssignmentMode> = {
  SUNDAY_SERVICE_1: 'SUNDAY',
  SUNDAY_SERVICE_2: 'SUNDAY',
  TUESDAY_SERVICE: 'TUESDAY',
  FRIDAY_SERVICE: 'TUESDAY',
  IGABURO: 'IGABURO',
};

export function resolveAssignmentMode(
  templateCode: string | null | undefined,
  operationType: string,
): ProtocolAssignmentMode {
  if (templateCode && TEMPLATE_ASSIGNMENT_MODES[templateCode]) {
    return TEMPLATE_ASSIGNMENT_MODES[templateCode];
  }
  return operationType === 'SPECIAL_EVENT' ? 'SPECIAL_EVENT' : 'TUESDAY';
}

export const PROTOCOL_MONTHLY_TEMPLATE_CODES = [
  'TUESDAY_SERVICE',
  'FRIDAY_SERVICE',
  'SUNDAY_SERVICE_1',
  'SUNDAY_SERVICE_2',
  'IGABURO',
] as const;

/** Protocol team size and choir composition caps (10 members total). */
export const PROTOCOL_TEAM_SIZING = {
  TEAM_SIZE_TARGET: 10,
  TEAM_SIZE_MIN: 10,
  TEAM_SIZE_MAX: 10,
  ONE_SINGING_CHOIR_MAX: 7,
  TWO_SINGING_CHOIRS_EACH_MAX: 4,
} as const;

/** Small roster fallback for seeded demo environments only. */
export const PROTOCOL_DEMO_TEAM_SIZE = 3;

export function isProtocolDemoSeedEnabled() {
  return process.env.SEED_DEMO === 'true';
}

export function resolveProtocolTeamTargetSize() {
  return isProtocolDemoSeedEnabled()
    ? PROTOCOL_DEMO_TEAM_SIZE
    : PROTOCOL_TEAM_SIZING.TEAM_SIZE_TARGET;
}
