export const MINISTRY_SERVICES_AUDIT = {
  ANNOUNCEMENT_CREATED: 'MINISTRY_ANNOUNCEMENT_CREATED',
  DOCUMENT_UPLOADED: 'MINISTRY_DOCUMENT_UPLOADED',
  MEETING_CREATED: 'MINISTRY_MEETING_CREATED',
  MEETING_COMPLETED: 'MINISTRY_MEETING_COMPLETED',
  ACTION_ITEM_CREATED: 'MINISTRY_ACTION_ITEM_CREATED',
  ACTION_ITEM_COMPLETED: 'MINISTRY_ACTION_ITEM_COMPLETED',
  REPORT_EXPORTED: 'MINISTRY_REPORT_EXPORTED',
  DEVOTION_PUBLISHED: 'MINISTRY_DEVOTION_PUBLISHED',
} as const;

export const MINISTRY_ACTIVITY_ENTITY = {
  ANNOUNCEMENT: 'MinistryAnnouncement',
  DOCUMENT: 'MinistryDocument',
  MEETING: 'MinistryMeeting',
  ACTION_ITEM: 'MinistryMeetingActionItem',
} as const;
