export { apiClient, setAccessToken, getAccessToken } from './client'
export { ApiError, ConflictError, AuthError, ValidationError } from './client'
export { authApi }              from './modules/auth'
export { invitesApi }           from './modules/invites'
export { membersApi }           from './modules/members'
export { occurrencesApi }         from './modules/occurrences'
export { choirActivityApi }     from './modules/choirActivity'
export { choirApi }             from './modules/choir'
export { choirSchedulingApi }   from './modules/choirScheduling'
export { protocolApi }          from './modules/protocol'
export { contributionsApi }     from './modules/contributions'
export { welfareApi }           from './modules/welfare'
export type { WelfareCareCase } from './modules/welfare'
export { disciplineApi }        from './modules/discipline'
export { notificationsApi }     from './modules/notifications'
export { searchApi }            from './modules/search'
export { familiesApi }          from './modules/families'
export { documentsApi }         from './modules/documents'
export { musicApi }             from './modules/music'
export { reportsApi }           from './modules/reports'
export { assetsApi }            from './modules/assets'
export { choirOperationsApi }   from './modules/choir-operations'
export { choirServiceOpsApi }   from './modules/choirServiceOps'
export { rehearsalsApi }        from './modules/rehearsals'
export { financeApi }           from './modules/finance'
export type { FamilyLedgerRow } from './modules/finance'
export { governanceApi }        from './modules/governance'
export { memberPortalApi }      from './modules/memberPortal'
export { devotionsApi }         from './modules/devotions'
export { auditApi }             from './modules/audit'
export type { AuditLogEntry }   from './modules/audit'

export type {
  LoginPayload, RegisterPayload, LoginResponse, AuthUser, AccessRouting,
} from './modules/auth'
export type { AccountInvite, CreateAccountInvitePayload } from './modules/invites'
export type { ContributionClaim, ContributionCampaignAdminItem, ContributionCatalogAdminItem } from './modules/contributions'
export type { SongAsset, SongAssetType } from './modules/music'
