export { apiClient, setAccessToken, getAccessToken } from './client'
export { ApiError, ConflictError, AuthError, ValidationError } from './client'
export { authApi }              from './modules/auth'
export { membersApi }           from './modules/members'
export { occurrencesApi }         from './modules/occurrences'
export { choirActivityApi }     from './modules/choirActivity'
export { choirApi }             from './modules/choir'
export { choirSchedulingApi }   from './modules/choirScheduling'
export { protocolApi }          from './modules/protocol'
export { contributionsApi }     from './modules/contributions'
export { welfareApi }           from './modules/welfare'
export { disciplineApi }        from './modules/discipline'
export { dashboardApi }         from './modules/dashboard'
export { notificationsApi }     from './modules/notifications'
export { searchApi }            from './modules/search'
export { familiesApi }          from './modules/families'
export { systemApi }            from './modules/system'
export { announcementsApi }     from './modules/announcements'
export { documentsApi }         from './modules/documents'
export { musicApi }             from './modules/music'
export { reportsApi }           from './modules/reports'
export { churchIntelApi }       from './modules/churchIntel'
export { churchScheduleApi }    from './modules/churchSchedule'
export { ministriesApi }        from './modules/ministries'
export { assetsApi }            from './modules/assets'
export { choirOperationsApi }   from './modules/choir-operations'
export { choirServiceOpsApi }   from './modules/choirServiceOps'
export { rehearsalsApi }        from './modules/rehearsals'
export { setupApi }             from './modules/setup'
export { financeApi }           from './modules/finance'
export { churchGivingApi }      from './modules/churchGiving'
export { governanceApi }        from './modules/governance'
export { memberPortalApi }      from './modules/memberPortal'
export { devotionsApi }         from './modules/devotions'

export type {
  LoginPayload, LoginResponse, AuthUser,
} from './modules/auth'
export type { ContributionClaim } from './modules/contributions'
export type { SongAsset, SongAssetType } from './modules/music'
