export const MINISTRY_FINANCE_AUDIT_ENTITY = 'MinistryFinance';

export const MINISTRY_FINANCE_AUDIT = {
  FUND_CREATED: 'MINISTRY_FUND_CREATED',
  BUDGET_CREATED: 'MINISTRY_BUDGET_CREATED',
  EXPENSE_SUBMITTED: 'MINISTRY_EXPENSE_SUBMITTED',
  EXPENSE_APPROVED: 'MINISTRY_EXPENSE_APPROVED',
  EXPENSE_REJECTED: 'MINISTRY_EXPENSE_REJECTED',
  TRANSFER_CREATED: 'MINISTRY_FUND_TRANSFER_CREATED',
  TRANSACTION_ADDED: 'MINISTRY_FUND_TRANSACTION_ADDED',
  REPORT_EXPORTED: 'MINISTRY_FINANCE_REPORT_EXPORTED',
} as const;

export const DEFAULT_MINISTRY_FUNDS = [
  { name: 'General Fund', type: 'GENERAL' as const },
  { name: 'Welfare Fund', type: 'WELFARE' as const },
] as const;
